In [2]:
import numpy as np

# Step 1: Create dataset
# Rows = Students, Columns = Subjects
# Subjects: Math, Science, English, Computer

marks = np.array([
    [78, 85, 90, 88],
    [60, 70, 65, 72],
    [90, 92, 88, 95],
    [50, 45, 55, 60],
    [88, 95, 94, 91]
])

students = np.array(["Aman", "Riya", "Karan", "Neha", "Vasu"])
subjects = np.array(["Math", "Science", "English", "Computer"])

# Step 2: Basic Analysis
print("Student Marks:\n", marks)

# Average marks per student
avg_marks = np.mean(marks, axis=1)
print("\nAverage Marks of Students:")
for i in range(len(students)):
    print(students[i], ":", avg_marks[i])

# Step 3: Topper
topper_index = np.argmax(avg_marks)
print("\nTopper:", students[topper_index])

# Step 4: Subject-wise Performance
print("\nSubject-wise Average:")
subject_avg = np.mean(marks, axis=0)
for i in range(len(subjects)):
    print(subjects[i], ":", subject_avg[i])

# Step 5: Pass/Fail (Pass if all subjects >= 50)
pass_status = np.all(marks >= 50, axis=1)

print("\nPass/Fail Status:")
for i in range(len(students)):
    status = "Pass" if pass_status[i] else "Fail"
    print(students[i], ":", status)

# Step 6: Grade System
def get_grade(avg):
    if avg >= 85:
        return 'A'
    elif avg >= 70:
        return 'B'
    elif avg >= 50:
        return 'C'
    else:
        return 'F'

print("\nGrades:")
for i in range(len(avg_marks)):
    print(students[i], ":", get_grade(avg_marks[i]))

# Step 7: Highest marks in each subject
print("\nHighest Marks in Each Subject:")
max_marks = np.max(marks, axis=0)
for i in range(len(subjects)):
    print(subjects[i], ":", max_marks[i])

# Step 8: Students scoring above 80 in all subjects
high_performers = students[np.all(marks > 80, axis=1)]
print("\nStudents scoring >80 in all subjects:", high_performers)

Student Marks:
 [[78 85 90 88]
 [60 70 65 72]
 [90 92 88 95]
 [50 45 55 60]
 [88 95 94 91]]

Average Marks of Students:
Aman : 85.25
Riya : 66.75
Karan : 91.25
Neha : 52.5
Vasu : 92.0

Topper: Vasu

Subject-wise Average:
Math : 73.2
Science : 77.4
English : 78.4
Computer : 81.2

Pass/Fail Status:
Aman : Pass
Riya : Pass
Karan : Pass
Neha : Fail
Vasu : Pass

Grades:
Aman : A
Riya : C
Karan : A
Neha : C
Vasu : A

Highest Marks in Each Subject:
Math : 90
Science : 95
English : 94
Computer : 95

Students scoring >80 in all subjects: ['Karan' 'Vasu']
